name: continuous-integration

on:
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize"]

jobs:
  commitlint-lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.2
        with:
          node-version: "14.x"

      - name: Checkout and install pouchdb
        run: |
          git clone --depth 1 https://github.com/pouchdb/pouchdb.git
          cd pouchdb
          npm install
          npm run build-node
          cd ..

      - name: Checkout pouchdb-nextjs-router
        uses: actions/checkout@v2
        with:
          path: 'pouchdb-nextjs-router'

      - name: Install dependencies
        run: |
          cd pouchdb-nextjs-router
          npm ci

      - name: Check PR Name
        uses: JulienKode/pull-request-name-linter-action@v0.2.0
        with:
            configuration-path: ./pouchdb-nextjs-router/commitlint.config.js
      - name: Lint
        run: npm run lint

      - name: Lint
        run: npm run test
