name: gh-actions
on:
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize"]

jobs:
  test:
    runs-on: ubuntu-latest
    name: pouchdb-nextjs-router
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2.1.2
        with:
          node-version: "12.x"
      - name: Install Dependencies
        run: npm ci
      - name: Check PR Name
        uses: JulienKode/pull-request-name-linter-action@v0.2.0
      - name: Lint
        uses: npm run lint
      - name: Test
        uses: ./github/actions/test
